if(EXISTS "/workspace/tests/market_data/market_data/order_book_tests[1]_tests.cmake")
  include("/workspace/tests/market_data/market_data/order_book_tests[1]_tests.cmake")
else()
  add_test(order_book_tests_NOT_BUILT order_book_tests_NOT_BUILT)
endif()
